require 'hoe'
require './lib/kittyverse/api/version.rb'

Hoe.spec 'kittyverse-api' do

  self.version = KittyverseClient::VERSION

  self.summary = "kittyverse-api - web client (helpers) for using the CryptoKitties unofficial (v0) and official (v1) public (HTTP JSON) APIs"
  self.description = summary

  self.urls    = { home: 'https://github.com/cryptocopycats/kittyverse'}

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = []

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
